### ISSUE TITLE
Mongod server process becomes unresponsive after few CreateIndex calls

### ISSUE THREAD

**Issue by narendrachava** [Mongo2Go/Mongo2Go#49] opened 2018-06-05 20:06 UTC
I'm not sure what is the root cause of this (could be a deadlock) but I did some digging and commenting out following lines in "StartAndWaitForReady" method of "ProcessControl.cs" class fixes the issue.

            process.CancelErrorRead();
            process.CancelOutputRead();

**Comment by JohannesHoppe** [comment] 2018-06-05 21:15
You might want to send a PR, so that your valuable research does not get lost. 👍 
However, I feel very uncomfortable to skip those lines. I'm more sure that your root cause is somewhere else and that your Mongod got screwed (and not Mongo2Go itselve). It might take too much time to create those indexes?

**Comment by JohannesHoppe** [comment] 2018-06-05 21:58
Hi. Thanks for you investigations and continued effort. It has been a very long time, since I wrote the quoted code. But I'm sure I did it to clean up. It looked good and it worked, that's the reason.

Looking at the code,
* [this](https://github.com/Mongo2Go/Mongo2Go/blob/3a11beb4d219c672e1ef7a8dd0648e697c855ce9/src/Mongo2Go/Helper/ProcessControl.cs#L36) wrapper-code (begin+cancel) could be removed for sure. `process.WaitForExit();` is important only
* [this](https://github.com/Mongo2Go/Mongo2Go/blob/3a11beb4d219c672e1ef7a8dd0648e697c855ce9/src/Mongo2Go/Helper/ProcessControl.cs#L77) might need the cancelling. but I'm open for changes if it helps you.

Can you test this intensively for both `MongoDbRunner.Start();` and `MongoDbRunner.StartForDebugging();`. Can you confirm that there is still some ErrorOutput / StandardOutput in the returned `MongoDbProcess`? Maybe, maybe somebody is using this. 

> All further redirected output to StandardOutput is saved in a buffer. [...] What happens if the buffer is full and there is no one reading from it. I'm trying to find that out.
I don't think that MongoDB will create so much output that this will be really a problem. Also the target is not to run Mongo2Go for longer time (use-case is testing and local development/testing).

**Comment by narendrachava** [comment] 2018-06-11 16:19
Still on my to-do list, will submit a PR when ready. thanks !

**Comment by narendrachava** [comment] 2018-06-14 20:03
@JohannesHoppe ,
Submitted a PR to fix the issue, but I see an issue with the build on CI/CD pipeline which apparently is happening for the last few builds. Something's up with the runner ?

**Comment by JohannesHoppe** [comment] 2018-06-14 20:19
Don't worry. It's just the linux build and I do not have any clue why this happens.
I can't verify if its just related to TravisCI or if it is a general problem (since I have no linux machine available).

By the way:
I'm super busy right now. Please give me 1-2 weeks to bake the next version, ok?

**Comment by narendrachava** [comment] 2018-06-28 19:58
@JohannesHoppe 
Did you get a chance to create the next version ?

**Comment by JohannesHoppe** [comment] 2018-06-29 15:07
see #52

I merged it right now. But at the moment I have 200% work. :-(

**Comment by Beastw00d** [comment] 2018-07-19 13:52
@JohannesHoppe do you have an estimate on when this will be released? Also wanted to say thanks for this wondering project. It has helped me a ton with local debugging.

**Comment by JohannesHoppe** [comment] 2018-07-19 22:04
I pushed Mongo2Go 2.2.5 to nuget.org. Many thanks for the patience! 👍

**Closed** 2018-07-19 22:03 UTC
