### ISSUE TITLE
Can't run unit tests for Mongo2Go project

### ISSUE THREAD

**Issue by UnderHeavyDevelopment** [Mongo2Go/Mongo2Go#40] opened 2017-07-27 14:34 UTC
I downloaded source code of Mongo2Go, but have trouble with running tests. They use MSpec, I can't discover them with adapter nor in console (dotnet test). There is a file in solution NO_TESTS.txt. Does it mean they cannot be run now?

Can you run these tests on latest build? Any hints how?

**Comment by Johlandabee** [comment] 2017-07-27 14:41
Take a look at #31. Tests are currently broken. You can give [Amongst](https://github.com/Johlandabee/Amongst) a shot if your want. I think it will either replace Mongo2Go or will be merged over at some point.

**Comment by UnderHeavyDevelopment** [comment] 2017-07-27 14:54
@Johlandabee: Thank you a lot for suggestion. I wanted to fix #39, but it's harder without tests.
So Mongo2Go can be considered as abandonned right now?

**Comment by JohannesHoppe** [comment] 2017-07-27 14:57
confirmed! it's going to be A or B in future! :smile:

**Comment by Johlandabee** [comment] 2017-07-27 15:01
@UnderHeavyDevelopment you can find the previous discussion about this topic here: #35

**Comment by UnderHeavyDevelopment** [comment] 2017-07-27 15:10
Ok, I see. Tests in Mongo2Go are broken, because of an error in tests/project itself or problem with MSpec adapter?

**Comment by JohannesHoppe** [comment] 2017-07-27 15:38
I removed the tests from execution in https://github.com/Mongo2Go/Mongo2Go/commit/76f4a47dfca1f46db2360a736b31ee9069566a5b because of https://github.com/machine/machine.specifications/issues/322. All test files are still there.

It should work again now. You would need to follow the instructions from https://github.com/machine/machine.specifications/wiki/.NET-Core-(.NET-CLI).

**Comment by JohannesHoppe** [comment] 2017-11-23 10:37
fixed via https://github.com/Mongo2Go/Mongo2Go/commit/85c9c6012c1d7b3a8482974cc729ef69ef2bf7c6

![image](https://user-images.githubusercontent.com/640639/33168434-2ac03d28-d041-11e7-8b6d-f8a6680162c4.png)

thx to @perliedman 👍

**Closed by JohannesHoppe** 2017-11-23 10:37 UTC
Labels: duplicate
