### ISSUE TITLE
One set of linux binaries - MongoDB distributes different binaries for different flavours

### ISSUE THREAD

**Issue by nachiappannk** [Mongo2Go/Mongo2Go#73] opened 2019-04-06 04:52 UTC
Hi,

In your code base, I see only one set of binaries for linux.
MongoDB distributes different binaries for Ubuntu 16.04 Linux, RHEL 7.2, and so on.

Now that one binary is working for different flavors of linux in this case.
What will be impact (difference in behavior) for for the mongodb test server running in Ubuntu and RHEL.

Regards,
Nachi

**Comment by JohannesHoppe** [comment] 2019-05-10 16:31
duplicate of #74

**Closed by JohannesHoppe** 2019-05-10 16:31 UTC
