### ISSUE TITLE
Error parsing command line: unrecognised option '--sslMode'

### ISSUE THREAD

**Issue by chrisseroka** [Mongo2Go/Mongo2Go#59] opened 2018-10-29 11:34 UTC
While running `MongoDbRunner.Start()` I get the following error:
`Error parsing command line: unrecognised option '--sslMode'`

It happened after updating Mongo2Go to newer version. The latest working version is `2.2.1`
OS: Windows 10

**Comment by JohannesHoppe** [comment] 2019-02-05 12:39
I can't reproduce this. Do you have more infos?

**Comment by JohannesHoppe** [comment] 2019-03-15 14:25
No answer. Closing this.

**Closed by JohannesHoppe** 2019-03-15 14:25 UTC
Labels: bug
