### ISSUE TITLE
singleNodeRepliaset true option doesn't work with --logpath argument 

### ISSUE THREAD

**Issue by Jishun** [Mongo2Go/Mongo2Go#108] opened 2020-12-20 05:47 UTC
in my code, when attempting to start the singleNodeReplicaset,  it always times out no matter how long is `singleNodeReplSetWaitTimeout` 

I found that I added --logpath argument to additionalMongodArguments 
it works after I removed this option 

it seems to be related to how replicasetReady is detected, when --logPath is specified, the process output captured by Mongo2go can't get that information:
https://github.com/Mongo2Go/Mongo2Go/blob/8f2f5724ee0b324378623da5ad31bba5871e3e42/src/Mongo2Go/Helper/MongoDbProcessStarter.cs#L52

**Comment by JohannesHoppe** [comment] 2020-12-20 06:04
As always, I will publish any PR that has green tests! 😉

**Comment by JohannesHoppe** [comment] 2021-04-08 07:10
@Jishun could you try this out again with Mongo2Go 3.1? The capturing of the output was changed by @corentinaltepe. I will close this issue for now. Please reply to this issue if the problem is still unresolved.

**Closed by JohannesHoppe** 2021-04-08 07:10 UTC

**Comment by Jishun** [comment] 2021-04-10 03:46
upgraded to mongo2go nuget 3.1.1, unfortunately the same error still 
` System.TimeoutException : Replica set initialization took longer than the specified timeout of 10 seconds. Please consider increasing the value of singleNodeReplSetWaitTimeout.`
when `--logPath` argument is specified

**Comment by JohannesHoppe** [comment] 2021-04-10 04:45
Ok, but now you can use your own logger?!

**Comment by Jishun** [comment] 2021-04-10 09:43
I did discover that with the new version , default injected logger captured a lot of logs from mango , which isn't what I want,  but easy to filter so I don't mind. 
 the problem is about the huge amount of stdoutput in the console , it's a lot of noises,  I'd like to keep the mongo output separately because in the real scenario the db is separate from the application.

**Comment by Jishun** [comment] 2021-04-10 09:44
I think the issue is that the logic is trying to determine the state of the db by reading its output, however it assumes it's always stdout and won't follow when it's redirected

**Comment by corentinaltepe** [comment] 2021-04-10 11:43
Hello @Jishun . I'm not certain I completely understand the issue, but I can give some context to help you out.

When calling:
```c#
MongoDbRunner.Start();
```

`MongoDbRunner` starts `mongod` with default log level `info`. It needs to read `mongod` logs to dertermine when the database is ready to accept queries (when one of the logs contains `"waiting for connections"`).

If you don't inject a custom `ILogger` to `MongoDbRunner.Start();`, then all `mongod` logs are wired to .NET's [Console](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#console) and [Debug](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#debug) outputs. That explains the large quantity of logs that make noise in your console.

Starting with v3.1 of `Mongo2Go`, you can now inject your own `ILogger` object. When calling the following:
```c#
ILogger mylogger = /* instanciate and configure your logger. */
MongoDbRunner.Start(logger: mylogger);
```

then `mongod` logs are not wired to .NET's Debug and Console output, but to `mylogger`. Then, you're free to configure `mylogger` the way you like:
1. don't route the logs anywhere: `MongoDbRunner.Start(logger: NullLogger.Instance);`
2. route logs to console output, with minimum level of `Error`.
3. route logs to a third-party library like `log4net`, `nlog`, `serilog`. Then, configure this library for even more targets/sinks such as files, HTTP API, and many more. That's my personal use-case.

Could you use the case 3. to output `mongod` logs to another file?

**Comment by Jishun** [comment] 2021-04-12 00:36
thanks

the issue initially was raised that Mongo2Go doesn't work with `--logpath` argument to mongo db, yet it still isn't working with it according to my test

however I did a quick test with the logger parameter and seeing my application logger now is logging clean messages, so far it looks meet my needs, thank you for your kind explanation.
